# Generated by Django 5.2.7 on 2025-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_partner_review_sitesettings_sociallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
