# Generated by Django 5.2.7 on 2025-12-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_excursion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_repr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона (строка)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_repr',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp (строка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат должен быть +xxxxxxxxxxxx', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Формат должен быть +xxxxxxxxxxxx', max_length=50, verbose_name='WhatsApp'),
        ),
    ]
