# Generated by Django 5.2.7 on 2025-12-07 10:56

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_phone_repr_sitesettings_whatsapp_repr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='cover_head',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Шапка'),
        ),
    ]
