# Generated by Django 5.2.7 on 2025-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_excursion_cover_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_gmap',
            field=models.TextField(blank=True, verbose_name='Ссылка Google-карт'),
        ),
    ]
