# Generated by Django 5.2.7 on 2025-12-10 13:44

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings_address_gmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Изображение баннера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_link',
            field=models.URLField(blank=True, verbose_name='Ссылка баннера'),
        ),
    ]
